# アプリ名（ログ用）
spring.application.name=attendance-system

# ===== DB接続設定（PostgreSQL） =====
spring.datasource.url=jdbc:postgresql://localhost:5432/attendance_system
spring.datasource.username=postgres
spring.datasource.password=human
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPAの基本設定 =====
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#タイムゾーン統一
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Tokyo
# DB接続ごとにセッションTZをTokyoに固定（DB全体設定は変えない）
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Asia/Tokyo';
